# Preface to the {{< var ay >}} BM329 Block B workshop {.unnumbered}

Welcome to the BM329 (Biomedical Microbiology) Block B workshop for {{< var ay >}}.

This year is the first presentation of this workshop material, and we would be very grateful to hear feedback [by email](mailto:{{< var admin.email >}}) or through the [GitHub repository Issues page]({{< var github.issues >}}).

## Overview

The workshop asks you to 

::: { .callout-warning title="Important Note"}
There is new material in this workshop that is not covered in lectures, and this material is examinable. Please take care to read the text in the expandable callout boxes, as well as that for the workshop, to be sure you have understood the topic and obtain full value from the exercise.

The workshop material will remain live online for the duration of BM329, and you can revisit it whenever you wish, for practice or revision.
:::

**You should be able to complete this workshop in under two hours.**

## Learning Objectives

By the end of this workshop, students will be able to:

- Describe influenza virus particles and how they replicate
- Explain the roles that antigenic shift and antigenic drift play in influenza virus evolution
- Discuss the effects of vaccination and antiviral drugs on influenza virus evolution and public health
- Build phylogenetic trees representing the evolution of influenza viruses

After reading the materials presented in this online component students will be able to understand:

1. How phylogenetic trees represent evolution as a series of divergences that branch out from a single common ancestor.
2. How _phylograms_ and _cladograms_ differ.
3. How the same tree can look different, depending how branches are rotated, but because the _topology_ remains the same, it represents the same evolutionary history.
4. How to produce a Hamming distance matrix from a table of characters.
5. How to use the UPGMA algorithm to produce a dendrogram from a distance matrix.

## Assessment

This workshop activity itself is not formally assessed although, as noted, the material it contains is examinable.
