# Summary

After reading these workshop materials, you should now understand:

1. How phylogenetic trees represent evolution as a series of divergences that branch out from a single common ancestor.
2. How _phylograms_ and _cladograms_ differ.
3. How the same tree can look different, depending how branches are rotated, but because the _topology_ remains the same, it represents the same evolutionary history.
4. How to produce a Hamming distance matrix from a table of characters.
5. How to use the UPGMA algorithm to produce a dendrogram from a distance matrix.

::: { .callout-warning title="Thank you" }
That's almost the end of this online material. Thank you for reading We hope you found it enjoyable and interesting, and that you now understand more about how phylogenetic trees can be constructed.

This year is the first presentation of this particular material, and we would be very grateful to hear feedback [by email](mailto:{{< var admin.email >}}) or through the [GitHub repository Issues page]({{< var github.issues >}}).
:::

::: { .callout-tip title="Completing the workshop" }
Please now follow the instructions for the practical part of the workshop, to build a phylogenetic tree for your `flu viruses.
:::